task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ["bbox"]

num_classes: 4 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: R:\Project\Hacktoberfest\bascorro\RESEARCH\CUSTOM_YOLO\D-FINE\data\HardHatSample\images\train
    ann_file: R:\Project\Hacktoberfest\bascorro\RESEARCH\CUSTOM_YOLO\D-FINE\data\HardHatSample\annotations\instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: R:\Project\Hacktoberfest\bascorro\RESEARCH\CUSTOM_YOLO\D-FINE\data\HardHatSample\images\val
    ann_file: R:\Project\Hacktoberfest\bascorro\RESEARCH\CUSTOM_YOLO\D-FINE\data\HardHatSample\annotations\instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
